spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
management.endpoints.web.exposure.include=*
logging.level.com.an=ERROR
spring.cloud.config.token=vault-plaintext-root-token
spring.application.name=bar
spring.config.import=optional:configserver:

server.port=7654